# Generated by Django 4.2.17 on 2025-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Salary", "员工工资"),
                            ("Maintenance", "维修费用"),
                            ("Utilities", "水电费"),
                            ("Other", "其他支出"),
                        ],
                        max_length=50,
                        verbose_name="支出类别",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("Room", "客房收入"), ("Food", "餐饮收入"), ("Other", "其他收入")],
                        max_length=50,
                        verbose_name="收入来源",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
        ),
    ]
