# Generated by Django 4.2.20 on 2025-03-07 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_expense_options_alter_income_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "订单详情",
                "verbose_name_plural": "订单详情",
            },
        ),
    ]
