# Generated by Django 4.2.17 on 2025-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(max_length=10, unique=True, verbose_name="房间号"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Single", "单人间"),
                            ("Double", "双人间"),
                            ("Suite", "套房"),
                            ("Deluxe", "豪华间"),
                        ],
                        max_length=50,
                        verbose_name="房间类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("facilities", models.TextField(verbose_name="设施")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "空闲"),
                            ("Booked", "已预订"),
                            ("Occupied", "已入住"),
                            ("Maintenance", "维修中"),
                        ],
                        default="Available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("floor", models.IntegerField(verbose_name="楼层")),
                ("capacity", models.IntegerField(verbose_name="容纳人数")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
        ),
    ]
