# Generated by Django 4.2.17 on 2025-01-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="pictures",
            field=models.ImageField(
                blank=True,
                help_text="房间主图",
                null=True,
                upload_to="pictures/",
                verbose_name="房间主图",
            ),
        ),
    ]
