# Generated by Django 4.2.17 on 2025-03-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_room_pictures"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "房间", "verbose_name_plural": "房间"},
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="价格"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[("single", "单人间"), ("double", "双人间"), ("suite", "套房")],
                max_length=20,
                verbose_name="房间类型",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "可用"),
                    ("occupied", "已占用"),
                    ("maintenance", "维护中"),
                ],
                default="available",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
