# Generated by Django 4.2.17 on 2025-03-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_room_options_alter_room_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "房间", "verbose_name_plural": "房间管理"},
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="价格"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("standard", "标准间"),
                    ("double", "双床房"),
                    ("deluxe", "豪华间"),
                    ("suite", "套房"),
                    ("family", "家庭房"),
                    ("business", "商务间"),
                ],
                max_length=50,
                verbose_name="房间类型",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "空闲"),
                    ("occupied", "已入住"),
                    ("reserved", "已预订"),
                    ("maintenance", "维护中"),
                ],
                default="available",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
