# Generated by Django 4.2.17 on 2025-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("position", models.CharField(max_length=100, verbose_name="职位")),
                ("phone", models.CharField(max_length=15, verbose_name="联系方式")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="工资"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="入职日期")),
                (
                    "status",
                    models.CharField(
                        default="Active", max_length=20, verbose_name="状态"
                    ),
                ),
            ],
        ),
    ]
