# Generated by Django 4.2.17 on 2025-01-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="入住日期")),
                ("check_out_date", models.DateField(verbose_name="离店日期")),
                ("number_of_guests", models.IntegerField(verbose_name="入住人数")),
                ("special_requests", models.TextField(blank=True, verbose_name="特殊要求")),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=20, verbose_name="预订状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooms.room",
                        verbose_name="房间",
                    ),
                ),
            ],
        ),
    ]
