# Generated by Django 4.2.17 on 2025-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("Pending", "待定"), ("CheckIn", "入住"), ("CheckOut", "离店")],
                default="Pending",
                max_length=20,
                verbose_name="预订状态",
            ),
        ),
    ]
