# Generated by Django 4.2.17 on 2025-03-06 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_customer_options_remove_customer_id_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0002_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"verbose_name": "预订", "verbose_name_plural": "预订管理"},
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                default=reservations.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="预订用户",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="顾客",
            ),
        ),
    ]
