# Generated by Django 4.2.20 on 2025-03-07 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_alter_reservation_options_reservation_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "待确认"),
                    ("Confirmed", "已确认"),
                    ("CheckIn", "已入住"),
                    ("CheckOut", "已退房"),
                    ("Cancelled", "已取消"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="预订状态",
            ),
        ),
    ]
