# Generated by Django 4.2.20 on 2025-03-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_customer_options_customer_user_and_more"),
        ("reservations", "0004_alter_reservation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "预订",
                "verbose_name_plural": "预订管理",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="总价",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="check_out_date",
            field=models.DateField(verbose_name="退房日期"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待确认"),
                    ("confirmed", "已确认"),
                    ("checked_in", "已入住"),
                    ("checked_out", "已退房"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
