# Generated by Django 4.2.17 on 2025-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "id_number",
                    models.CharField(max_length=18, unique=True, verbose_name="身份证号"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="联系方式")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "membership_level",
                    models.CharField(blank=True, max_length=50, verbose_name="会员等级"),
                ),
                ("points", models.IntegerField(default=0, verbose_name="积分")),
            ],
        ),
    ]
